### ISSUE TITLE
Inquery!

### ISSUE THREAD

**Issue by kmrajibfaysal** [progmamun/programming-hero#1]
What is the purpose of this repo vai?

**Comment by almamunrub** [comment]
class er note gula ay khan, a folder kora raki,, google drive a jeta korta bolcilo,,, readme.md file a kori,, r poject er jono new repo create kori,, assignment er jono private repo..

**Comment by almamunrub** [comment]
serial kora rakta easy hoba jono emon korci,,

**Comment by kmrajibfaysal** [comment]
got it, brother! barakallah fi!
